### ISSUE TITLE
feature/export aktualisierung schlägt fehl.

### ISSUE THREAD

**Issue by fwolf-ilias** [studer-raimann/SrGeogebra#1]
Fehler auf test6.ilias.de, wenn das Plugin auf Branch feature/export in der Administration aktualisiert wird.

<pre>
DEAR TESTER! AN ERROR OCCURRED... PLEASE INCLUDE THE FOLLOWING OUTPUT AS ADDITIONAL INFORMATION IN YOUR BUG REPORT.

Exception thrown with message "String could not be parsed as XML"

Stacktrace:
#14 Whoops\Exception\ErrorException in /srv/www/test6.ilias.de/html/ilias/Services/Database/classes/class.ilDBUpdate.php:496
#13 SimpleXMLElement:__construct in /srv/www/test6.ilias.de/html/ilias/Services/Database/classes/class.ilDBUpdate.php:496
#12 eval in /srv/www/test6.ilias.de/html/ilias/Services/Database/classes/class.ilDBUpdate.php:496
#11 ilDBUpdate:applyUpdateNr in /srv/www/test6.ilias.de/html/ilias/Services/Database/classes/class.ilDBUpdate.php:363
#10 ilDBUpdate:applyUpdate in /srv/www/test6.ilias.de/html/ilias/Services/Component/classes/class.ilPlugin.php:522
#9 ilPlugin:updateDatabase in /srv/www/test6.ilias.de/html/ilias/Customizing/global/plugins/Services/COPage/PageComponent/SrGeogebra/vendor/srag/removeplugindataconfirm/src/BasePluginUninstallTrait.php:32
#8 ilSrGeogebraPlugin:updateDatabase in /srv/www/test6.ilias.de/html/ilias/Services/Component/classes/class.ilPlugin.php:1074
#7 ilPlugin:update in /srv/www/test6.ilias.de/html/ilias/Services/Component/classes/class.ilObjComponentSettingsGUI.php:539
#6 ilObjComponentSettingsGUI:update in /srv/www/test6.ilias.de/html/ilias/Services/Component/classes/class.ilObjComponentSettingsGUI.php:527
#5 ilObjComponentSettingsGUI:updatePlugin in /srv/www/test6.ilias.de/html/ilias/Services/Component/classes/class.ilObjComponentSettingsGUI.php:91
#4 ilObjComponentSettingsGUI:executeCommand in /srv/www/test6.ilias.de/html/ilias/Services/UICore/classes/class.ilCtrl.php:203
#3 ilCtrl:forwardCommand in /srv/www/test6.ilias.de/html/ilias/Services/Administration/classes/class.ilAdministrationGUI.php:246
#2 ilAdministrationGUI:executeCommand in /srv/www/test6.ilias.de/html/ilias/Services/UICore/classes/class.ilCtrl.php:203
#1 ilCtrl:forwardCommand in /srv/www/test6.ilias.de/html/ilias/Services/UICore/classes/class.ilCtrl.php:164
#0 ilCtrl:callBaseClass in /srv/www/test6.ilias.de/html/ilias/ilias.php:20

-- GET Data --

ref_id                   : 1141
admin_mode               : settings
ctype                    : Services
cname                    : COPage
slot_id                  : pgcp
pname                    : SrGeogebra
cmd                      : updatePlugin
cmdClass                 : ilobjcomponentsettingsgui
cmdNode                  : 9f:5t
baseClass                : ilAdministrationGUI
lang                     : de
limit                    : 50

-- POST Data --

empty

-- Files --

empty

-- Cookies --

ilClientId               : test6
PHPSESSID                : 
462920095                : {"any_entry_engaged":true,"tools_engaged":false,"more_available":false,"entries":{"0:0":[0,0,0],"0:1":[0,0,0],"0:1:1":[0,0,0],"0:1:2":[0,0,0],"0:2":[0,0,0],"0:2:0":[0,0,0],"0:2:1":[0,0,0],"0:3":[0,0,0],"0:4":[0,0,0],"0:5":[0,0,0],"0:6":[0,1,0],"0:6:0":[0,1,0],"0:6:1":[0,0,0],"0:6:2":[0,0,0],"0:6:3":[0,0,0],"0:6:4":[0,0,0],"0:6:5":[0,0,0],"0:6:7":[0,0,0],"0:6:8":[0,1,0],"0:6:9":[0,0,0],"0:7":[0,0,0],"0:8":[0,0,1]},"tools":{"":[0,0,1,"T:0"]},"known_tools":[""],"last_active_top":"0:6"}
SESSID                   : 
il_mb_slates             : {"engaged":true}

-- Session --

_authsession_authenticated: 1
_authsession_user_id     : 48216
_authsession_expired     : 0
pctpc_listened_event     : Array
                         (
                             [time] => 1614955010
                             [event] => afterLogin
                         )
                         
post_vars                : Array
                         (
                         )
                         
referer                  : /ilias.php?ref_id=1141&admin_mode=settings&ctype=Services&cname=COPage&slot_id=pgcp&cmd=listPlugins&cmdClass=ilobjcomponentsettingsgui&cmdNode=9f:5t&baseClass=ilAdministrationGUI
referer_ref_id           : 1141
tbl_limit                : 50
il_rep_mode              : tree
il_rep_ref_id            : 1
help_screen_id           : cmps/plugins/.1141
help_search_term         : 
SessionType              : 2
orig_request_target      : 
has_to_accept_agr_in_session: 1
lang                     : de
ilUserRequestTargetAdjustment_passed: 1
awr_online_user_ts       : 2021-03-05 15:36:50
awrn_last_update         : 1614955320
awrn_nr_users            : 2
awrn_nr_husers           : 0
table                    : Array
                         (
                             [cmpspl] => Array
                                 (
                                     [48216] => Array
                                         (
                                             [offset] => 0
                                         )
                         
                                 )
                         
                         )
                         

-- Server/Request Data --

USER                     : www-data
HOME                     : /var/www
SCRIPT_NAME              : /ilias.php
REQUEST_URI              : /ilias.php?ref_id=1141&admin_mode=settings&ctype=Services&cname=COPage&slot_id=pgcp&pname=SrGeogebra&cmd=updatePlugin&cmdClass=ilobjcomponentsettingsgui&cmdNode=9f:5t&baseClass=ilAdministrationGUI
QUERY_STRING             : ref_id=1141&admin_mode=settings&ctype=Services&cname=COPage&slot_id=pgcp&pname=SrGeogebra&cmd=updatePlugin&cmdClass=ilobjcomponentsettingsgui&cmdNode=9f:5t&baseClass=ilAdministrationGUI
REQUEST_METHOD           : GET
SERVER_PROTOCOL          : HTTP/1.1
GATEWAY_INTERFACE        : CGI/1.1
REMOTE_PORT              : 44304
SCRIPT_FILENAME          : /srv/www/test6.ilias.de/html/ilias/ilias.php
SERVER_ADMIN             : webmaster@ilias.de
CONTEXT_DOCUMENT_ROOT    : /srv/www/test6.ilias.de/html/ilias
CONTEXT_PREFIX           : 
REQUEST_SCHEME           : https
DOCUMENT_ROOT            : /srv/www/test6.ilias.de/html/ilias
REMOTE_ADDR              : 89.245.12.204
SERVER_PORT              : 443
SERVER_ADDR              : 89.238.76.7
SERVER_NAME              : test6.ilias.de
SERVER_SOFTWARE          : Apache/2.4.18 (Ubuntu)
SERVER_SIGNATURE         : <address>Apache/2.4.18 (Ubuntu) Server at test6.ilias.de Port 443</address>
                         
PATH                     : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_COOKIE              : ilClientId=test6; PHPSESSID=fb74b (SHORTENED FOR SECURITY); 462920095={"any_entry_engaged":true,"tools_engaged":false,"more_available":false,"entries":{"0:0":[0,0,0],"0:1":[0,0,0],"0:1:1":[0,0,0],"0:1:2":[0,0,0],"0:2":[0,0,0],"0:2:0":[0,0,0],"0:2:1":[0,0,0],"0:3":[0,0,0],"0:4":[0,0,0],"0:5":[0,0,0],"0:6":[0,1,0],"0:6:0":[0,1,0],"0:6:1":[0,0,0],"0:6:2":[0,0,0],"0:6:3":[0,0,0],"0:6:4":[0,0,0],"0:6:5":[0,0,0],"0:6:7":[0,0,0],"0:6:8":[0,1,0],"0:6:9":[0,0,0],"0:7":[0,0,0],"0:8":[0,0,1]},"tools":{"":[0,0,1,"T:0"]},"known_tools":[""],"last_active_top":"0:6"}; SESSID=; il_mb_slates={"engaged":true}
HTTP_CONNECTION          : keep-alive
HTTP_DNT                 : 1
HTTP_REFERER             : https://test6.ilias.de/ilias.php?ref_id=1141&admin_mode=settings&ctype=Services&cname=COPage&slot_id=pgcp&cmd=listPlugins&cmdClass=ilobjcomponentsettingsgui&cmdNode=9f:5t&baseClass=ilAdministrationGUI
HTTP_ACCEPT_ENCODING     : gzip, deflate, br
HTTP_ACCEPT_LANGUAGE     : de,en-US;q=0.7,en;q=0.3
HTTP_ACCEPT              : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_USER_AGENT          : Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
HTTP_HOST                : test6.ilias.de
SSL_SESSION_RESUMED      : Resumed
SSL_SESSION_ID           : 
SSL_SERVER_A_SIG         : sha256WithRSAEncryption
SSL_SERVER_A_KEY         : rsaEncryption
SSL_SERVER_I_DN          : CN=R3,O=Let's Encrypt,C=US
SSL_SERVER_S_DN          : CN=test6.ilias.de
SSL_SERVER_V_END         : May 30 11:18:24 2021 GMT
SSL_SERVER_V_START       : Mar  1 11:18:24 2021 GMT
SSL_SERVER_M_SERIAL      : 03350950F22260D2A79AE1134364EA9AECF3
SSL_SERVER_M_VERSION     : 3
SSL_CLIENT_VERIFY        : NONE
SSL_CIPHER_ALGKEYSIZE    : 128
SSL_CIPHER_USEKEYSIZE    : 128
SSL_CIPHER_EXPORT        : false
SSL_CIPHER               : ECDHE-RSA-AES128-GCM-SHA256
SSL_COMPRESS_METHOD      : NULL
SSL_SECURE_RENEG         : true
SSL_PROTOCOL             : TLSv1.2
SSL_VERSION_LIBRARY      : OpenSSL/1.0.2g
SSL_VERSION_INTERFACE    : mod_ssl/2.4.18
SSL_SERVER_SAN_DNS_2     : user6.ilias.de
SSL_SERVER_SAN_DNS_1     : test60.ilias.de
SSL_SERVER_SAN_DNS_0     : test6.ilias.de
SSL_SERVER_I_DN_CN       : R3
SSL_SERVER_I_DN_O        : Let's Encrypt
SSL_SERVER_I_DN_C        : US
SSL_SERVER_S_DN_CN       : test6.ilias.de
SSL_TLS_SNI              : test6.ilias.de
HTTPS                    : on
HTTP_AUTHORIZATION       : 
SCRIPT_URI               : https://test6.ilias.de/ilias.php
SCRIPT_URL               : /ilias.php
FCGI_ROLE                : RESPONDER
PHP_SELF                 : /ilias.php
REQUEST_TIME_FLOAT       : 1614955321.8823
REQUEST_TIME             : 1614955321

-- Environment Variables --

empty
</pre>

**Comment by mstuder** [comment]
Da das Plugin für mehrere ILIAS Versionen verfübar ist, ist es hier erforderlich jeweils mit composer up die Libraries nachzuladen. Kannst du dies im Geogebra Plugin-Verzeichnis einmal tun?

Bitte wende dich bei zukünftigen Fragen hierzu direkt an die Support-E-Mail der studer + raimann ag.

Liebe Grüsse
